#!/usr/bin/env php
<?php
    include_once '/etc/freepbx.conf';
    error_reporting(E_ALL);
    $syno = \FreePBX::Synologyactivebackupforbusiness();

    $error_code = -1;
    $data_return = array(
        'error' => array(),
        'exec'  => array(),
        'app'   => array(),
    );

    $file = $syno->getHookFilename("version");
    if (file_exists($file)) { unlink($file); }
    
    if (! $syno->isAgentInstalled())
    {
        $error_code = 501;
    }
    else
    {
        $cmd = $syno->getABBCliPath() . " -v 2>&1";
        exec($cmd, $out, $ret);

        $data_return['exec'] = array('cmd' => $cmd, 'ret' => $ret, 'out' => $out);

        if (! is_array($out))
        {
            $error_code = 502;
        }
        elseif($ret !== 0)
        {
            $error_code = 503;
        }
        elseif(count($out) != 1)
        {
            $error_code = 504;
        }
        else
        {
            $version = explode(":", $out[0]);
            $version = array_map('trim', $version);
            $data_return['app'] = array(
                'name' => $version[0],
                'version' => $version[1],
            );
            $error_code = 0;
        }
    }

    $data_return['error'] = $syno->getErrorMsgByErrorCode($error_code, true);

    if ($error_code !== 0)
    {
        $syno->logger->error( sprintf("Synology ABB / hook / get-cli-version - Code (%s): %s", $error_code, $data_return['error']['msg']) ) ;
    }

    $syno->writeFileHook($file, $data_return);

    // dbug($data_return);

    exit();
?>
