#!/usr/bin/env php
<?php
    include_once '/etc/freepbx.conf';
    error_reporting(E_ALL);
    $syno = \FreePBX::Synologyactivebackupforbusiness();

    $data_return = array(
        'error_code' => -1,
        'error_msg' => ""
    );

    $file = $syno->get_hook_file("version");
    if (file_exists($file)) { unlink($file); }
    

    if (! $syno->isAgentInstalled())
    {
        $data_return['error_code'] = 501;
        $data_return['error_msg'] = _("Synology Agent not Installed!");
    }
    else
    {
        $cmd = $syno->get_abbclipath() . " -v 2>&1";
        exec($cmd, $out, $ret);

        if($ret === 0 && is_array($out) && count($out) == 1)
        {
            $version = explode(":", $out[0]);
            $version = array_map('trim', $version);
            $data_return['app']     = $version[0];
            $data_return['version'] = $version[1];
            $data_return['error_code'] = 0;
        }
        else
        {
            $data_return['error_code'] = 502;
            $data_return['error_msg'] = _("Synology Agent not return info!");
        }
    }

    file_put_contents($file, json_encode($data_return));
    chown($file, 'asterisk');

    if ($data_return['error_code'] != 0)
    {
        $syno->logger->error( sprintf("Synology ABB / hook / get-cli-version - Error Code (%s): %s", $data_return['error_code'], $data_return['error_msg']) ) ;
    }

    // dbug($data_return);

    exit();
?>
